// Responsive sources for the gallery derivatives generated by
// scripts/generate-gallery-images.mjs. Keep WIDTHS in sync with that script —
// it is the only other place the ladder is declared.
export const IMAGE_WIDTHS = [200, 300, 400, 800, 1200];

const FALLBACK_WIDTH = 800;

/**
 * @param {string} base path without extension or width suffix,
 *   e.g. "/gallery/produkt-1/produkt-1-1"
 */
export function imageSources(base) {
  return {
    webpSrcSet: IMAGE_WIDTHS.map((w) => `${base}-${w}.webp ${w}w`).join(", "),
    fallbackSrc: `${base}-${FALLBACK_WIDTH}.jpg`,
  };
}
