/**
 * Copy that was written inline in components rather than in locales.js, and so
 * had no single home. Both the seeder (which writes it into Sanity) and the
 * fallback in content.server.js (which serves it when Sanity is unreachable)
 * read it from here — otherwise the two drift and a page renders different text
 * depending on which source answered.
 */

/** The home page's visually hidden <h1>, previously inline in app/routes/_index.jsx. */
export const HOME_SR_HEADING = {
  pl: "Neatual - produkcja i dystrybucja uniformów",
  en: "Neatual - uniform production and distribution",
  de: "Neatual - Uniformproduktion und -vertrieb",
};

/**
 * Fills {name} / {n} placeholders. The parameterised labels were functions in
 * locales.js, which no CMS field can express; as templates they become ordinary
 * strings an editor can translate, and this is the one place that expands them.
 */
export function fillTemplate(template, values) {
  if (typeof template !== "string") return "";
  return template.replace(/\{(\w+)\}/g, (match, key) =>
    values[key] === undefined ? match : String(values[key])
  );
}

/** Screen-reader labels, previously inline ternaries in Header, _index and kontakt. */
export const A11Y_LABELS = {
  call: { pl: "Zadzwoń", en: "Call", de: "Anrufen" },
  email: { pl: "Napisz e-mail", en: "Send email", de: "E-Mail senden" },
  expand: {
    pl: "Pokaż pełny opis",
    en: "Show full description",
    de: "Vollständige Beschreibung anzeigen",
  },
  langNav: { pl: "Wybierz język", en: "Language selector", de: "Sprachauswahl" },
  mainNav: { pl: "Nawigacja główna", en: "Main navigation", de: "Hauptnavigation" },
  selectProduct: {
    pl: "{name} — wybierz, aby zobaczyć",
    en: "{name} — select to view",
    de: "{name} — auswählen zum Anzeigen",
  },
  selectPhoto: {
    pl: "Pokaż zdjęcie {n}",
    en: "Show photo {n}",
    de: "Foto {n} anzeigen",
  },
  photoAlt: {
    pl: "{name} — zdjęcie {n}",
    en: "{name} — photo {n}",
    de: "{name} — Foto {n}",
  },
};

/**
 * The postal address, in schema.org's components rather than one string.
 *
 * It was stored as a single display string in the CMS *and* hardcoded a second
 * time as a PostalAddress in root.jsx's JSON-LD, so moving premises would have
 * updated the visible address while quietly leaving the old one in the
 * structured data. One source, both consumers.
 *
 * `countryName` is seeded as "Polska" in all three locales because that is what
 * the site shows today; translating it is now an edit in the Studio rather than
 * a silent change made during a refactor.
 */
export const ADDRESS = {
  streetAddress: "ul.Siedlecka 172",
  postalCode: "08-110",
  addressLocality: "Żelków-Kolonia",
  addressCountry: "PL",
  countryName: { pl: "Polska", en: "Polska", de: "Polska" },
};

/** The one-line form shown on the page, derived so it cannot drift from the parts. */
export function formatAddress(address, locale) {
  if (!address) return "";
  const country =
    typeof address.countryName === "string"
      ? address.countryName
      : address.countryName?.[locale];
  return [
    address.streetAddress,
    [address.postalCode, address.addressLocality].filter(Boolean).join(" "),
    country,
  ]
    .filter(Boolean)
    .join(", ");
}

/**
 * Product copy. Was generated by per-locale functions in products.js; the same
 * strings as templates, seeded into Sanity and mirrored here for the fallback.
 */
export const PRODUCT_COPY = {
  numbers: [1, 2, 3, 4],
  photoCount: 4,
  name: { pl: "Wzór nr {n}", en: "Pattern no. {n}", de: "Muster Nr. {n}" },
  price: {
    pl: "Wycena indywidualna",
    en: "Price on request",
    de: "Preis auf Anfrage",
  },
  descriptionLines: {
    pl: ["50% bawełna / 50% len", "Uszyto w Polsce."],
    en: ["50% cotton / 50% linen", "Made in Poland."],
    de: ["50% Baumwolle / 50% Leinen", "Gefertigt in Polen."],
  },
  alt: {
    pl: "Uniform wzór nr {n} — 50% bawełna, 50% len, uszyty w Polsce",
    en: "Uniform pattern no. {n} — 50% cotton, 50% linen, made in Poland",
    de: "Uniform Muster Nr. {n} — 50% Baumwolle, 50% Leinen, gefertigt in Polen",
  },
};

/**
 * Per-page title suffix and meta description. Was branching logic inside
 * root.jsx's getPageMeta(); now content, seeded into Sanity and mirrored here
 * so the fallback produces byte-identical <title> and description tags.
 */
export const PAGE_META = {
  gallery: {
    suffix: { pl: "Galeria", en: "Gallery", de: "Galerie" },
    description: {
      pl: "Galeria produktów Neatual - uniformy szyte w Polsce z polskich materiałów.",
      en: "Neatual product gallery - uniforms made in Poland from Polish materials.",
      de: "Neatual Produktgalerie - in Polen aus polnischen Materialien gefertigte Uniformen.",
    },
  },
  contact: {
    suffix: { pl: "Kontakt", en: "Contact", de: "Kontakt" },
    description: {
      pl: "Skontaktuj się z Neatual - ul. Siedlecka 172, Żelków-Kolonia. Tel. +48 739 903 148.",
      en: "Contact Neatual - ul. Siedlecka 172, Żelków-Kolonia. Phone +48 739 903 148.",
      de: "Kontakt Neatual - ul. Siedlecka 172, Żelków-Kolonia. Tel. +48 739 903 148.",
    },
  },
};
