// `base` is a path without extension or width suffix; the responsive variants
// are generated by scripts/generate-gallery-images.mjs and resolved through
// app/lib/images.js. The masters live in art/gallery-originals/ and are never
// served.
const photoBase = (product, photo) =>
  `/gallery/produkt-${product}/produkt-${product}-${photo}`;

const createProduct = (index) => ({
  name: `Wzór nr ${index}`,
  price: "XX PLN",
  description: "50% bawełna / 50% len<br>Uszyto w Polsce.",
  thumbnailBase: photoBase(index, 1),
  alt: `Uniform wzór nr ${index} - 50% bawełna, 50% len, uszyto w Polsce`,
  photos: [
    { base: photoBase(index, 1) },
    { base: photoBase(index, 2) },
    { base: photoBase(index, 3) },
    { base: photoBase(index, 4) },
  ],
});

export const products = [
  createProduct(1),
  createProduct(2),
  createProduct(3),
  createProduct(4),
];
