// Product copy was Polish-only and locale-blind, so /en/gallery and
// /de/galerie shipped Polish names, descriptions and alt text under an
// English/German shell while carrying hreflang that promised a translation.
// See §1.4 of docs/AUDIT-SEO-PERFORMANCE-ACCESSIBILITY.md.
//
// `descriptionLines` is an array rather than an HTML string so the gallery and
// the modal can render it without dangerouslySetInnerHTML — two of the eight
// injection sites the security audit recorded.
//
// `price` replaces the "XX PLN" placeholder that was shipping to production in
// all three locales. These are made-to-order uniforms with no list price, so
// the honest value is a quote prompt, not a number.

const COPY = {
  pl: {
    name: (n) => `Wzór nr ${n}`,
    price: "Wycena indywidualna",
    descriptionLines: ["50% bawełna / 50% len", "Uszyto w Polsce."],
    alt: (n) =>
      `Uniform wzór nr ${n} — 50% bawełna, 50% len, uszyty w Polsce`,
    photoAlt: (name, i) => `${name} — zdjęcie ${i}`,
  },
  en: {
    name: (n) => `Pattern no. ${n}`,
    price: "Price on request",
    descriptionLines: ["50% cotton / 50% linen", "Made in Poland."],
    alt: (n) =>
      `Uniform pattern no. ${n} — 50% cotton, 50% linen, made in Poland`,
    photoAlt: (name, i) => `${name} — photo ${i}`,
  },
  de: {
    name: (n) => `Muster Nr. ${n}`,
    price: "Preis auf Anfrage",
    descriptionLines: ["50% Baumwolle / 50% Leinen", "Gefertigt in Polen."],
    alt: (n) =>
      `Uniform Muster Nr. ${n} — 50% Baumwolle, 50% Leinen, gefertigt in Polen`,
    photoAlt: (name, i) => `${name} — Foto ${i}`,
  },
};

const PRODUCT_NUMBERS = [1, 2, 3, 4];

// `base` is a path without extension or width suffix; the responsive variants
// are generated by scripts/generate-gallery-images.mjs and resolved through
// app/lib/images.js. The masters live in art/gallery-originals/.
const photoBase = (product, photo) =>
  `/gallery/produkt-${product}/produkt-${product}-${photo}`;

export function getProducts(locale) {
  const copy = COPY[locale] ?? COPY.pl;

  return PRODUCT_NUMBERS.map((n) => ({
    name: copy.name(n),
    price: copy.price,
    descriptionLines: copy.descriptionLines,
    alt: copy.alt(n),
    thumbnailBase: photoBase(n, 1),
    photos: [1, 2, 3, 4].map((p) => ({ base: photoBase(n, p) })),
  }));
}

export function getPhotoAlt(locale, productName, index) {
  const copy = COPY[locale] ?? COPY.pl;
  return copy.photoAlt(productName, index);
}
