import { localizedField } from "../lib/localizedField.js";

export const product = {
  name: "product",
  title: "Product",
  type: "document",
  fields: [
    {
      name: "order",
      title: "Order",
      type: "number",
      description: "Position in the gallery grid. Lowest first.",
      validation: (Rule) => Rule.required().integer().positive(),
    },
    {
      name: "imageBase",
      title: "Image folder",
      type: "string",
      description:
        "Folder under /public/gallery, e.g. produkt-1. Photos are produkt-1-1 … produkt-1-4; responsive variants are generated by scripts/generate-gallery-images.mjs.",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "photoCount",
      title: "Number of photos",
      type: "number",
      initialValue: 4,
      validation: (Rule) => Rule.required().integer().min(1),
    },
    localizedField({ name: "name", title: "Name" }),
    localizedField({
      name: "price",
      title: "Price",
      description:
        "Every installation is quoted individually, so this is a prompt to get in touch rather than a number. Do not invent a figure.",
    }),
    localizedField({
      name: "descriptionLines",
      title: "Description lines",
      description:
        "One line per entry. An array rather than rich text so the gallery and modal can render it without raw HTML.",
      of: { type: "array", of: [{ type: "string" }] },
    }),
    localizedField({
      name: "alt",
      title: "Image alt text",
      description:
        "Describes the finished installation — the pattern and the room — for screen readers and image search. Claim only what the photograph shows; materials and dimensions are not known.",
      of: { type: "text", rows: 2 },
    }),
  ],
  orderings: [
    {
      title: "Gallery order",
      name: "orderAsc",
      by: [{ field: "order", direction: "asc" }],
    },
  ],
  preview: {
    select: { title: "name.pl", subtitle: "imageBase", order: "order" },
    prepare: ({ title, subtitle, order }) => ({
      title: `${order}. ${title ?? "Untitled"}`,
      subtitle,
    }),
  },
};
