import { localizedField } from "../lib/localizedField.js";

/*
  One gallery category — a tile on /galeria and a page of its own beneath it.

  The type is still named `product` while the Studio calls it a category. The
  name is the document's `_type` in every existing document and in CONTENT_QUERY;
  renaming it would orphan the six documents already in the dataset for a label
  nobody sees. The title, the structure entry and the field descriptions are what
  an editor reads, and those all say category.
*/
export const product = {
  name: "product",
  title: "Gallery category",
  type: "document",
  fields: [
    {
      name: "order",
      title: "Order",
      type: "number",
      description: "Position in the gallery grid. Lowest first.",
      validation: (Rule) => Rule.required().integer().positive(),
    },
    {
      name: "slug",
      title: "Reference id",
      type: "string",
      description:
        "Internal name for this category, e.g. 'kwiatowe'. Not part of any address — service pages point at categories by this id, so changing it breaks those links. Lowercase letters, digits and hyphens only. Leave it alone unless you know what references it.",
      validation: (Rule) =>
        Rule.required()
          .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, { name: "slug" })
          .error("Lowercase letters, digits and hyphens only."),
    },
    localizedField({
      name: "slugs",
      title: "URL slug, per language",
      description:
        "The last part of the address, written in each language: 'montaz-fototapet-kwiatowych' gives /galeria/montaz-fototapet-kwiatowych, while the English field gives /en/gallery/<that word>. Write the phrase somebody would search for — this is the one part of the URL search engines read. Lowercase letters, digits and hyphens only, no Polish or German accented characters. Changing one changes a published URL; the old address redirects rather than breaking.",
      of: {
        type: "string",
        validation: (Rule) =>
          Rule.regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, { name: "slug" }).error(
            "Lowercase letters, digits and hyphens only — no accents."
          ),
      },
    }),
    {
      name: "imageBase",
      title: "Image folder",
      type: "string",
      description:
        "Folder under /public/gallery, e.g. kwiatowe. Photos are kwiatowe-1 … kwiatowe-4; responsive variants are generated by scripts/generate-gallery-images.mjs. Usually the same word as the slug, but separate from it so the URL can be renamed without moving files.",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "photoCount",
      title: "Number of photos",
      type: "number",
      initialValue: 4,
      validation: (Rule) => Rule.required().integer().min(1),
    },
    localizedField({ name: "name", title: "Name" }),
    localizedField({
      name: "price",
      title: "Price",
      description:
        "Every installation is quoted individually, so this is a prompt to get in touch rather than a number. Do not invent a figure.",
    }),
    localizedField({
      name: "descriptionLines",
      title: "Description lines",
      description:
        "One line per entry. An array rather than rich text so the gallery and modal can render it without raw HTML.",
      of: { type: "array", of: [{ type: "string" }] },
    }),
    localizedField({
      name: "alt",
      title: "Image alt text",
      description:
        "Describes the finished installation — the pattern and the room — for screen readers and image search. Claim only what the photograph shows; materials and dimensions are not known.",
      of: { type: "text", rows: 2 },
    }),

    /*
      The category page's own copy. All three are optional: left empty, the site
      composes a title and description from the name, the alt text and the
      description lines above, which are already written in three languages. That
      is a worse description than one written for the purpose, and a better one
      than six pages sharing the gallery's.
    */
    localizedField({
      name: "intro",
      title: "Category intro",
      description:
        "Optional paragraph under the heading on the category's own page. Leave empty to show just the description lines.",
      of: { type: "text", rows: 3 },
    }),
    localizedField({
      name: "metaTitle",
      title: "Meta title",
      description:
        "Optional. Used for <title>, og:title and twitter:title on this category's page. Left empty: the site title followed by the category name.",
    }),
    localizedField({
      name: "metaDescription",
      title: "Meta description",
      description:
        "Optional. Left empty: the alt text and the description lines, joined into a sentence.",
      of: { type: "text", rows: 3 },
    }),
  ],
  orderings: [
    {
      title: "Gallery order",
      name: "orderAsc",
      by: [{ field: "order", direction: "asc" }],
    },
  ],
  preview: {
    select: { title: "name.pl", subtitle: "slug", order: "order" },
    prepare: ({ title, subtitle, order }) => ({
      title: `${order}. ${title ?? "Untitled"}`,
      subtitle,
    }),
  },
};
